function g = G_2D(x, X, delta)
    g = sum((...
    X(2:end)+X(2:end).^2 ...
    - exp(-x(1) * delta) * X(1:end-1) ...
    - exp(-2 * x(1) * delta) * X(1:end-1).^2 ...
    + (exp(-2 * x(1) * delta) - 1) * x(2) / x(1)) ...
    .* [X(1:end-1).^2; X(1:end-1)], 2);
end